INSERT INTO `VENDORS` (`Vcode`, `Vname`) VALUES
('AL', 'Alfalux'),
('AP', 'Ape'),
('AZ', 'Azuliber'),
('BR', 'Brennero'),
('CG', 'Campogalliano'),
('CC', 'Ceramicasa'),
('CD', 'Cerdisa'),
('CF', 'Cifre'),
('CR', 'Cristacer'),
('EC', 'Edilcuoghi'),
('ED', 'Edimax'),
('ER', 'Ermes'),
('FZ', 'Fly Zone'),
('GR', 'Grespania'),
('GZ', 'Gazzini'),
('HR', 'H&R Johnson'),
('IS', 'Isla'),
('LF', 'La Fabrica'),
('PM', 'Pamesa'),
('PO', 'Polis'),
('RC', 'Rondine / Sadon'),
('SA', 'Savoia');

